travis:
  secure:
    BINSTAR_TOKEN: s5enpk9zBVeWg5jGDutJphsxOtNypFoPz32y/Ok0WGuoKyWUmtNiPOyIoo42gGZRIU4ERGOyflUKUez/LSReRsHEnwONZaCcfzvN66oeSObXVn8pBKcF7epnplaUK6jVj+QnU8R4CwUag7hQzBHR++oRHDooiQosOumYN7fBORuMTfXf0fOpW20f3o3EoR1umgAWko8ppyf5yzLgE7Cqzzu5X1KM8SI4h9UT6ZhKe4SyIPBiBQTPI4B14pX6FJwJgN+Tv+eNxkpDTIQcZB3raBGK1bfCOww95PJ9Qoxh6KW2TbpKNcXkkxIvE0r+AsM1Fq9vyWNAMC9HC/UUpqJlL3KIVWHnU2vYH9Go80Knpx8vuA77Lu0uunrTiwhUzWAG3ndE8VPbKRZ4cUKQcdcMLI2TcAHPDS3bdwpv2X2YTZ9GSAcHlNAq8e57r0OGawXsS7uMNnpdc/WV2sBV5wpCiCH4fPE69WJ2kjgeqLQKpa5JfkQ0LtFWMAzUs7pu3Calb5Iy7H8Mq60aBrNCwfpXyp9xJ++f/lcawzn2Blkdk+RQR6u29vWck0JjdXF4j4GDlPucy7VLubI+MLOh4yeCeLN3DQwvuR1jMM8UVUNgE8wbxj5k5Towtrw2XUA++gXikWk/mIdGKoJZua3xbZBKJ5Z64rXQyEnJzsh7jIXxVGM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
